name: PHP test suite
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install php-net-ldap2
    - run: touch config/config-auth.inc.php
    - run: php test/run.php
